#!/usr/bin/env bash

# Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"

# variables for primary(MP) and secodary(MS) monitors
#MP=DisplayPort-0
#MS=DisplayPort-1
MP=DP-2

# setup monitors layout
~/.screenlayout/displays.sh
#xrandr --output $MP --primary --mode 3440x1440 --rate 165.00 --set TearFree on

# option for smooth window dragging on different refresh rates.
#example for 144hz: 1000\144=7
bspc config pointer_motion_interval 5

# set primary mode
bspc monitor $MP -d 1 2 3 4 5 6 7 8 9
#bspc monitor $MS -d second
#bspc monitor $MT -d third
#bspc wm -O $MP $MS #$MT
# trick to make some JetBrains software work
wmname LG3D

# set US and RU keyboard layouts and WIN+SPACE changing conmbination
setxkbmap -layout us,ru -option grp:win_space_toggle

# set keyboard repetition rate
xset r rate 250 50

# borders and gaps
bspc config border_width 1
bspc config window_gap 5
bspc config split_ratio 0.6

# dinamically change top padding given polybar height
height=$(grep height ~/.config/polybar/config | awk '{print $3}')

# top padding only on primary monitor since polybar is only on primary monitor
bspc config -m $MP top_padding $height
#bspc config -m $MS top_padding 0
#bspc config -m $MT top_padding 0

# mouse interactions 
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Window rules ----------------------------------------------#

# remove all rules first
bspc rule -r *:*

bspc rule -a Floating state=floating follow=on focus=on 
bspc rule -a Fullscreen state=fullscreen follow=on focus=on 

bspc rule -a Navigator state=floating sticky=on follow=on
bspc rule -a firefox state=floating follow=on 
bspc rule -a steam state=floating follow=on 
bspc rule -a Spotify desktop='^9' state=floating follow=on 
bspc rule -a Dragon-drop state=floating sticky=on follow=on 
bspc rule -a feh state=floating follow=on
bspc rule -a mpv state=floating follow=on
bspc rule -a 'Minecraft Launcher' state=floating follow=on
bspc rule -a Pavucontrol state=floating follow=on
bspc rule -a QjackCtl state=floating follow=on
bspc rule -a easyeffects state=floating follow=on

# Autostart -------------------------------------------------#
# Lauch keybindings daemon
killall -9 sxhkd
sxhkd &

# Set wallpaper
feh --bg-fill ~/Pictures/Wallpapers/trolley.jpg 


# Start picom
#killall -9 picom
#picom &

# Start polybar
~/.config/polybar/launch.sh &

# fix cross-looking pointer
xsetroot -cursor_name left_ptr &

# my attempts in dynamic displays configuration, maybe will finish it someday..
#declare -a CONNECTED_MONITORS=( $(xrandr | grep ' connected' | awk '{print $1}') )
#setup workspaces
#if [[ "$1" = 0 -a $(xrandr | grep 'DisplayPort-1 connected' | wc -l) -eq 1 ]]; then
#    xrandr --output DisplayPort-0 --primary --pos 1440x1120 --mode 3440x1440 --rate 165 --output DisplayPort-1 --pos 0x0 --left-of DisplayPort-0
#    xrandr --output DisplayPort-1 --rotate left
#    xrandr --output DisplayPort-0 --pos 1440x1120
#    bspc monitor DisplayPort-0 -d 1 2 3 4 5 6  
#    bspc monitor DisplayPort-1 -d 7 8 9 10    
#    bspc wm -O DisplayPort-0 DisplayPort-1
#else

