#!/usr/bin/env bash

# Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"

# Load .Xresources file ------------------------------------#
xrdb ~/.Xresources
# Get colors from xrdb -------------------------------------#
FOREGROUND=$(xrdb -get foreground)
BACKGROUND=$(xrdb -get background)
BLACK=     $(xrdb -get color0)
RED=       $(xrdb -get color1)
GREE=      $(xrdb -get color2)
YELLOW=    $(xrdb -get color3)
BLUE=      $(xrdb -get color4)
MAGENTA=   $(xrdb -get color5)
CYAN=      $(xrdb -get color6)
WHITE=     $(xrdb -get color7)

# setup workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9
# trick to make some JetBrains software work
wmname LG3D
# set US and RU keyboard layouts and WIN+SPACE changing conmbination
setxkbmap -layout us,ru -option grp:win_space_toggle
# set keyboard repetition rate
xset r rate 250 50

bspc config border_width 1
bspc config window_gap 0
bspc config split_ratio 0.50

bspc config focused_border_color "$BLUE" 
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer false

# mouse interactions 
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Window rules ----------------------------------------------#

# remove all rules first
bspc rule -r *:*

bspc rule -a Dragon-drag-and-drop desktop='^1' state=floating follow=on focus=on sticky=on; 
bspc rule -a Skype desktop='^6' follow=on focus=on; 
bspc rule -a 'Microsoft Teams - Preview' desktop='^7' follow=on focus=on; 
bspc rule -a qBittorrent desktop='^8' follow=on focus=on; 

bspc rule -a 'Alacritty:Floating' state=floating follow=on focus=on; 
bspc rule -a 'Alacritty:Fullscreen' state=fullscreen follow=on focus=on; 
bspc rule -a feh state=fullscreen follow=on focus=on; 
bspc rule -a Mpv state=fullscreen follow=on focus=on; 

bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off

# Autostart -------------------------------------------------#

# Kill if already running
killall -9 xsettingsd sxhkd dunst xfce4-power-manager

# Lauch notification daemon
dunst \
-geom "280x50-10+42" -frame_width "1" -font "Iosevka Custom 9" \
-lb "$BACKGROUND" -lf "$FOREGROUND" -lfr "$BLUE" \
-nb "$BACKGROUND" -nf "$FOREGROUND" -nfr "$BLUE" \
-cb "$BACKGROUND" -cf "$RED" -cfr "$RED" &

# Lauch xsettingsd daemon
xsettingsd &

# Lauch keybindings daemon
sxhkd &

# Enable power management
xfce4-power-manager &

# Start bspwm scripts
bspcolors &
~/.config/polybar/launch.sh &
bspcomp &

