#!/usr/bin/env bash

# Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"

# setup workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9
# trick to make some JetBrains software work
wmname LG3D
# set US and RU keyboard layouts and WIN+SPACE changing conmbination
setxkbmap -layout us,ru -option grp:win_space_toggle
# set keyboard repetition rate
xset r rate 250 50

bspc config border_width 1
bspc config window_gap 5
bspc config split_ratio 0.50

height=$(grep height ~/.config/polybar/config | awk '{print $3}')
bspc config top_padding $height

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer false

# mouse interactions 
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Window rules ----------------------------------------------#

# remove all rules first
bspc rule -r *:*

bspc rule -a Dragon-drag-and-drop desktop='^1' state=floating follow=on focus=on sticky=on; 
bspc rule -a Skype desktop='^6' follow=on focus=on; 
bspc rule -a 'Microsoft Teams - Preview' desktop='^7' follow=on focus=on; 
bspc rule -a qBittorrent desktop='^8' follow=on focus=on; 

bspc rule -a 'Alacritty:Floating' state=floating follow=on focus=on; 
bspc rule -a 'Alacritty:Fullscreen' state=fullscreen follow=on focus=on; 
bspc rule -a feh state=fullscreen follow=on focus=on; 
bspc rule -a Mpv state=fullscreen follow=on focus=on; 

bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off

# Autostart -------------------------------------------------#

# Kill if already running
killall -9 xsettingsd sxhkd dunst xfce4-power-manager

# Lauch xsettingsd daemon
xsettingsd &

# Lauch keybindings daemon
sxhkd &

# Enable power management
xfce4-power-manager &

# Set wallpaper
feh --bg-scale ~/Pictures/bouquet.jpg

# Start picom
#picom &
# Start polybar
~/.config/polybar/launch.sh &
