import = ["/home/paul/.config/alacritty/fonts.toml"]
live_config_reload = true

[colors.primary]
background = "#000000"

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "full"
dynamic_title = true
startup_mode = "Windowed"

[window.dimensions]
columns = 90
lines = 40

[window.padding]
x = 7
y = 7
