#! /bin/sh

sxhkd &
#xcompmgr -c &
polybar default &

bspc monitor -d 1 2 3 4 5 6 7 8 9 

bspc config border_width 		2
bspc config window_gap 			6
bspc config normal_border_color 	"#2b2b2b"
bspc config focused_border_color 	"#7b7b7b"

bspc config split_ratio			0.5
bspc config borderless_monocle 		true
bspc config gapless_monocle		true
