#! /bin/sh
picom -experemental_backend --backend glx -e 1.0 &
sxhkd &
unclutter &
wmname LG3D
setxkbmap -layout us,ru -option grp:win_space_toggle
feh --bg-fill ~/wallpapers/0151.jpg
xset r rate 300 50
home/frostlin/.config/polybar/launch.sh
# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Launch Polybar, using default config location ~/.config/polybar/config
polybar mybar &


bspc monitor -d • • • • • • • • • •
bspc config border_width 		2
bspc config window_gap 			4
bspc config normal_border_color 	"#3b3b3b"
#bspc config focused_border_color 	"#5d5d81"
bspc config focused_border_color 	"#AAAAAA"

bspc config split_ratio			0.5
bspc config borderless_monocle 		true
bspc config gapless_monocle		true
bspc config top_padding 		20


bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
