#! /bin/sh

sxhkd &
#xcompmgr -c &
wmname LG3D
bspc monitor -d 1 2 3 4 5 6 7 8 9 

bspc config border_width 		5
bspc config window_gap 			20
bspc config normal_border_color 	"#3b3b3b"
bspc config focused_border_color 	"#5d5d81"

bspc config split_ratio			0.5
bspc config borderless_monocle 		true
bspc config gapless_monocle		true
